### ISSUE TITLE
StripeCharge and some StripeCustomer related action types are defined in the Types namespace and incomplete

### ISSUE THREAD

**Issue by jpasichnyk** [ServiceStack/Stripe#10]
Most of the other actions are not in the Types namespace, and also have Routes, IReturn<> definitions, etc.

**Comment by jpasichnyk** [comment]
@mythz can you provide some guidance on what you're target naming convention is here?  I was assuming that all the "actions" that can be done should be prefixed with Get/Create/Update/List/Delete, but then looking at things like CreateStripeCharge vs what the test cases use ChargeStripeCustomer (the object with the route defined, etc), it seems to break this pattern.  It seems to me that it should have been CreateStripeCharge that got the route and is passed into the Post().

**Comment by mythz** [comment]
Only Request DTO's have `IReturn<T>` markers and the Request DTO is the name of the operation so is usually a verb. The Request and Response DTO's are in the base namespace and any other supporting types should be in the Types namespace.

When it makes sense to I'll try to make it descriptive as to what it does, where I think `ChargeStripeCustomer` is more indicative with what it does than `CreateStripeCharge`. A lot of top-level API's follow the CRUD naming conventions but Refund has a few API's like `CaptureStripeCharge`, `RefundStripeCharge`.
