### ISSUE TITLE
ServiceStack.Text.JsConfig.With(…) Method is missing?

### ISSUE THREAD

**Issue by thammadi** [ServiceStack/Stripe#19]
Hi,

I'm testing Create Stripe Customer API:
return _stripeGateway.Post(new CreateStripeCustomer
            {
                Email = email,
                Description = description
            });

The above code throws the below exception:

Method not found: 'ServiceStack.Text.JsConfigScope ServiceStack.Text.JsConfig.With(System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<ServiceStack.Text.ParseAsType>, System.Nullable`1<ServiceStack.Text.ParseAsType>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<ServiceStack.Text.DateHandler>, System.Nullable`1<ServiceStack.Text.TimeSpanHandler>, System.Nullable`1<ServiceStack.Text.PropertyConvention>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.String, System.Func`2<System.Type,System.String>, System.Func`2<System.String,System.Type>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<Int32>, ServiceStack.EmptyCtorFactoryDelegate, System.String[])'.

I have installed ServiceStack.Stripe using 'Manage Nuget Packages' in Visual Studio.

Following are the dll versions show in my Visual Studio properties window:
Stripe: 4.0.42.0
ServiceStack.Client: 4.0.42.0
ServiceStack.Interfaces: 4.0.0.0
ServiceStack.Text: 4.0.42.0

Someone on Stackoverflow mentioned it could be because of dll version mismatch. Could  ServiceStack.Interfaces dll causing the issue? If yes, then how and where to get the latest dll version (4.0.42.0)?

Please help !

Cheers,

**Comment by mythz** [comment]
Hi, this is resolved with the latest v4.0.31 that's [now available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

**Comment by thammadi** [comment]
Thanks for the update.

Cheers,
