### ISSUE TITLE
Serializing Nested Types Fails

### ISSUE THREAD

**Issue by sproutslypaul** [ServiceStack/Stripe#23]
I created some new types to deal with Stripe Accounts, but they serialize incorrectly and get rejected by the Stripe servers.  Here are the relevant Types.

``` C#
// Extend the Existing Api with call the Create a Stripe Account
[Route("/accounts")]
public class CreateStripeAccount : IPost, IReturn<StripeAccount>
{
    public string Country { get; set; }
    public bool Managed { get; set; }
    public string Email { get; set; }
    public StripeTOSAcceptance TOSAcceptance { get; set; }
    public StripeLegalEntity LegalEntity { get; set; }
}

public class StripeTOSAcceptance
{
    public DateTime Date { get; set; }
    public string IP { get; set; }
    public string UserAgent { get; set; }
}

public class StripeLegalEntity
{    
    public StripeDOB DOB { get; set; }    
}

public class StripeAccount : StripeId
{
    public Dictionary<string, string> Keys { get; set; }
}
```

If I submit a CreateStripeAccount request like this:
``` C#
var entity = new StripeLegalEntity { DOB = new StripeDOB { Day = "1", Month = "1", Year = "1970" }};
var custAccount = gateway.Post(new CreateStripeAccount
{
    Country = "US",
    Email = newCust.Email,
    Managed = true,
    TOSAcceptance = tos,
    LegalEntity = entity
}, Guid.NewGuid().ToString());
```

The problem is with the `DOB` property of `StripeLegalEntity`.  It gets serialized as 

```
...&legal_entity[dob]={day:1,month:1,year:1970}
```

resulting in this error
``` javascript
{
  "error": {
    "type": "invalid_request_error",
    "message": "'dob' must be a hash.",
    "param": "legal_entity[dob]"
  }
}
```

instead of a success response if I submit this

```
...&legal_entity[dob][day]=1&legal_entity[dob][month]=1&legal_entity[dob][year]=1970
```

How can I tell this library to serialize these types properly?  The `StripeTOSAcceptance` object serializes properly, but it's only a 1 deep graph.  I'm guessing that this has something to do with ServiceStack.Text and how it decides to emit these Complex objects to the UrlParams sequence, but am not sure.

Thanks,

Paul

**Comment by mythz** [comment]
Unfortunately support for this style of serialization of complex types isn't built into the client. 

Out of curiosity where are you seeing the docs showing the POST body of [Create Account](https://stripe.com/docs/api/node#create_account) and how to format the complex type body? I'm only seeing Create Account having 3 arguments?

**Comment by sproutslypaul** [comment]
There are only a few required arguments, but the docs indicate that you can send over anything that you can send in an account update (which would surface this same problem as well).  They say that there are a lot of account vars that will be required before an account becomes fully validated.

See:
https://stripe.com/docs/connect/managed-accounts

> There are many other fields you likely want to set when creating a managed account. We discuss some of the more nuanced ones in other guides in this section.

Also See:
https://stripe.com/docs/connect/updating-accounts
https://stripe.com/docs/api#account

I figured out the alternative post format just by intuition and trial & error.  Honestly, I'd much rather just post a Json document than serialize to a jsv query params... seems like fitting a square peg in a round hole.

Paul

**Comment by mythz** [comment]
Hi, I've added support for Stripe-style nested complex types in this commit: https://github.com/ServiceStack/ServiceStack.Text/commit/2920ec857cccfb69003e46c4299e6d2f12ff4231

So nested types like Date of Birth should now serialize fine, I've got a test for [Creating an Account](https://github.com/ServiceStack/Stripe/blob/master/tests/Stripe.Tests/StripeGatewayAccountTests.cs) which is now passing. But don't have any time to add more thorough tests atm, although hopefully this will be enough to get you started.

I'm trying to deploy to MyGet but it's being unresponsive so may take an hour or 2 before this is deployed, however you can still get the latest .dlls with this change from this repo in [/lib](https://github.com/ServiceStack/Stripe/tree/master/lib). I'll update this message when it's deployed on MyGet.

**Comment by sproutslypaul** [comment]
That's awesome, thanks Demis!  I'll look for it on Nuget.

**Comment by mythz** [comment]
To be clear it wont be on NuGet until the next release so you'll need to use the [pre-release NuGet packages on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet)

**Comment by sproutslypaul** [comment]
Ahhh, thanks for clarifying.  Much appreciated.
