### ISSUE TITLE
[ENH] Add MetaData and other fields into CreateStripeCustomer

### ISSUE THREAD

**Issue by cdmackie** [ServiceStack/Stripe#25]
Some properties are missing from a Stripe Customer object, which would be useful. 

MetaData
BusinessVatId
Currency

Add to CreateStripeCustomer, CreateStripeCustomerWithToken and UpdateStripeCustomer

**Comment by mythz** [comment]
Support for these new properties have been added in this commit: https://github.com/ServiceStack/Stripe/commit/d82960430f407eca0ab20271e91a5ec36e978c49

Note: it's invalid to send a currency, but it's now being returned in the Customer response.

This change is available from v4.0.61 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

**Comment by cdmackie** [comment]
Thank you.
