### ISSUE TITLE
UpdateStripeCustomer Metadata malformed

### ISSUE THREAD

**Issue by JoakimOgren** [ServiceStack/Stripe#26]
Metadata problem for ServiceStack/Stripe when having multiple entries in Metadata Dictionary.

```C#
gateway.Post(new UpdateStripeCustomer
{
    Id = "xxxx",
    Metadata = new Dictionary<string, string>
    {
        { "Data1", "Value1" },
        { "Data2", "Value2" }
    }
}
```

Metadata seen by Stripe dashboard
``Data1 = "Value1metadata[Data2]=Value2"``

Test function [Can_Create_and_UpdateCustomer_with_Metadata()](https://github.com/ServiceStack/Stripe/blob/master/tests/Stripe.Tests/StripeGatewayCustomerTests.cs) would spot this bug if it was testing for more than one dictionary member.

**Comment by mythz** [comment]
This should now fixed with this commit: https://github.com/ServiceStack/ServiceStack.Text/commit/e910e31fb15b8550f7ffaaa5fb3a86ce8bc2c3fd

This fix is available from v4.5.1 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

Thx for the pointer!
