### ISSUE TITLE
Just need some clarification regarding this PCL library

### ISSUE THREAD

**Issue by xplatsolutions** [ServiceStack/Stripe#33]
I can use it in my Xamarin iOS or Android application creating a custom View to gather the credit card information right? I know it can be done I'm just trying to find out if I'm not breaking any policy etc because there are Xamarin iOS/Android components (https://github.com/xamarin/XamarinStripe) but really old so trying to understand they way to go.

**Comment by mythz** [comment]
I don't see why you'd be breaking any policy, I just wouldn't be storing any credit card info on the device, just send the sensitive info directly to Stripe.

**Comment by xplatsolutions** [comment]
Sounds good, the advantage is really nice for reusing code in the client mobile side between iOS and Android. Thank you for the quick response.
