### ISSUE TITLE
Is this a bug?  Getting products uses the plans route?

### ISSUE THREAD

**Issue by 4deeptech** [ServiceStack/Stripe#38]
https://github.com/ServiceStack/Stripe/blob/f467493bf1aaabb8d2735f843fc3e56fe4657fff/src/Stripe/StripeGateway.cs#L403

**Comment by mythz** [comment]
Yeah, resolved in [this commit](https://github.com/ServiceStack/Stripe/commit/85706038a3faa268ece7ec0a485c3363a1cf5434).

This change is available from v5.4.1 that's now [available on MyGet](https://docs.servicestack.net/myget).
