### ISSUE TITLE
Getting payment methods as list not working

### ISSUE THREAD

**Issue by Shigerua** [ServiceStack/Stripe#42]
In the documentation the "GetStripeCards" is not a valid Class name.
There is something similar called "GetStripeCustomerCards" but those goes to the incorrect endpoint.

So it looks like there is currently no way to get a list of payment methods for a specific customer.

I'm using the .net standard version (.Core)

**Comment by mythz** [comment]
[GetStripeCustomerCards works](https://github.com/ServiceStack/Stripe/blob/fa7eb2d84fa516e36652f241ae9250077e81bd56/tests/Stripe.Tests/StripeGatewayCardTests.cs#L154-L157).
