### ISSUE TITLE
CancelStripeSubscription

### ISSUE THREAD

**Issue by tobiaszuercher** [ServiceStack/Stripe#46]
not sure if this is the right place to report since all other issues are unanswered.

anyway:

the cancel subscription dto is missing a crucial parameter "CancelAtPeriodEnd"

https://stripe.com/docs/billing/subscriptions/cancel

**Comment by mythz** [comment]
I've added the property in this commit: https://github.com/ServiceStack/Stripe/commit/78f721cb5583dd5b202902c7d313dfe4411218c3

Note: I'm maintaining the existing APIs but not actively tracking Stripe's new REST APIs unless I need to use them. If you need to use any missing ones, feel free to send PRs for any missing properties / APIs in future, in most cases it just requires adding C# DTOs and Properties.
