### ISSUE TITLE
No way to access Prices

### ISSUE THREAD

**Issue by srarnold** [ServiceStack/Stripe#48]
Was trying to find a way to access the Prices attached to a product, I can't seem to find any reference to Stripe Price object.

**Comment by mythz** [comment]
As per our docs this library only covers core APIs https://github.com/ServiceStack/Stripe#stripe

We welcome PRs for additional features where most new APIs can be implemented with [declarative DTOs](https://github.com/ServiceStack/Stripe#open-ended-declarative-message-based-apis).
