### ISSUE TITLE
PCI Compliance using Servicestack.Stripe

### ISSUE THREAD

**Issue by andyfensham** [ServiceStack/Stripe#51]
From what I read in the stripe documentation, it seems as if you use stripe.net or Servicestack.stripe, that you need to be PCI compliant, unless you create a token for a charge from a client side library like stripe.js and the pass to servicestack.   Do we need to be PCI compliant when using Servicestack Stripe

**Comment by mythz** [comment]
This is just a wrapper around Stripe's API it doesn't store anything itself, PCI compliance relates to how you manage CC details, e.g:
https://squareup.com/au/en/townsquare/pci-compliance
