### ISSUE TITLE
Allow POST operations to pass an idempotency header

### ISSUE THREAD

**Issue by jpasichnyk** [ServiceStack/Stripe#9]
https://stripe.com/docs/api/curl#idempotent_requests

To safely retry an API request without accidentally performing the same operation twice, you can attach a unique key to any POST request made to the Stripe API via the Idempotency-Key: <key> header.

**Comment by jpasichnyk** [comment]
working on this, will create a pull if i can figure a good solution

**Comment by jpasichnyk** [comment]
@mythz do these automatically make it into the current MyGet package after merging, or is there some manual step that needs to be taken to do that?  Assuming if they are automatically there, i just need uninstall/reinstall that package to get the latest?

**Comment by jpasichnyk** [comment]
nevermind, I see the new overload in the MyGet package now.  :)

**Comment by mythz** [comment]
There is a manual step to deploy to MyGet, let me know when you want to redeploy.

**Comment by jpasichnyk** [comment]
This works for me (in myget)
